   <hr>
Content &copy; Individual Authors. All Rights Reserved.<br>
Page generated by the <a href="http://katmore.com/sft/staycms">StayCMS Content Management System</a> in <?php $this->showExectime(); ?>.<br>
<small>
StayCMS is &copy; 2011 P.D.Bird.II and is released under the terms of the FreeBSD license.<br>
This is the "barebones" theme and is distributed with the staycms package.<br>
The "barebones" theme is released into the public domain and thus may be hacked up and edited without attribute (just the theme).<br>
Staycms themes are available at katmore's <a href="http://katmore.com/sft/staycms/themes">official staycms themes repository</a>.<br>
</small>
   </body>
</html>