   </div><!--middle-->
   <div id="bottom">
   <p><?php $this->showCopyright($f_format="%s"); ?></p>
   Page generated by the <a href="http://katmore.com/sft/staycms">StayCMS Content Management System</a> in <?php $this->showExectime(); ?>.<br>
   
   StayCMS is &copy; 2011 P.D.Bird.II and is released under the terms of the FreeBSD license.<br>
   This is the "diviate" theme which is &copy; 2011 P.D.Bird.II. It is released into the Public Domain.
   </div><!--bottom-->
</div><!--#container-->
   </body>
</html>