This is the Home Page (based on the 'home' portion of the name).<br>
You can modify it by editing the ./content/sample/home.inc.php file.<br>
<br>
You can modify the look and feel by editing <?php $this->showThemeurl(); ?>/page.inc.php<br>
You could also make a new theme by copying the diviate directory into a new folder...<br>
then edit sf-config.php to change the theme name whatever the new folder's name is.<br>
<br>
New content can be added by creating adding files in the content\sample folder.<br>
You would first need to decide on a valid contentid (unique name that is only alphanumeric plus hypthen and dashes)<br>
Then you would create a file newname.inc.php in the folder (newname being replaced with your contentid), then edit it.<br>
It can be arbitrarily edited, it will be evaluated as php script within the sfpage class.<br>
(and thus access to functionality as if it's a part of that class).<br>
<br>
URLs referencing other contentid's within the same namespace can easily be generated by stayCMS<br>
For example, to access the "sample-page" content, simple use <code>"&lt;?php $this-&gt;showContentLink("sample-page");?&gt;"</code> (in place of the URL)<br>
<br>
A page showcasing a "module" (StayCMS's method of extending functionality) is available.<br>
It is a module named "sfform" which facilitates the use of HTML forms within StayCMS.<br>
It can be seen here: <a href="<?php $this->showContentLink("module-example");?>">module example (using an HTML form)</a><br>
<br>
See the <a href="http://katmore.com/sft/staycms">official StayCMS project listing</a> at katmore.com for documentation and other information.
